version: "3"
services:
  mongo:
    image: mongo

  spring:
    build: ./spring
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo

  node:
    build: ./node
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
